### ISSUE TITLE
problem with file format 

### ISSUE THREAD

**Issue by leclercfl** [soumitag/SLIDE#2]
Hi,
I've tried to visualize some of my data both with the online version and the standalone SLIDE version on my computer but I couldn't get it to give me an output. I suppose it's a problem with the file format but I couldn't figure it out. I have attached the sample conditions and a truncated version of the data. Please let me know if you can have a look. Thanks. 
Fabrice. 

[sample.zip](https://github.com/soumitag/SLIDE/files/3634687/sample.zip)

**Comment by soumitag** [comment]
Hi,
The header names in the sample files are longer than what SLIDE currently supports. If you shorten/truncate them it will work. I tried your data with smaller header names and it worked. 
Also, SLIDE supports Ensembl identifiers without the version information so the part of the identifier including and after (.) has to be removed
[sample_modified.zip](https://github.com/soumitag/SLIDE/files/3636809/sample_modified.zip)
Attached here are your files that I have modified. Please let me know in case you face any issues using SLIDE.

**Comment by leclercfl** [comment]
OK, thanks a lot.
